---
title: "Haar Wavelet Analysis Generalization"
author: "Zach Diener"
date: "June 8, 2015"
output: html_document
---
#Background Motivation

I will be taking the code previously written on Haar Wavelet analysis, and modifying is so that it may be generally applicable to a range of data sets.

#Code
```{r}
#input number of frequency bands
j= c(1:5)

#input the original signal 
s <- c(8,20,32,36,32,20,8,4)
Averages = matrix(0,length(j),length(s))

#Averages<-t(Averages)
rownames(Averages) <- 0: (nrow(Averages)-1)
colnames(Averages) <- 1:ncol(Averages)
Averages[1,] <- s

nrows <- nrow(Averages)

#Calculate Averages
for (j in 1:((nrows)-1)){
  for (n in (2*j):length(s)){
    #print(Averages[1, (n-(((2*j)-1)):n)])
   Averages[(j+1),n] <- mean(Averages[1, (n-((2*j)-1)):n]) 
    }
  }

#Calculate Differences
Differences <- matrix(c(0),nrow(Averages)-1,ncol(Averages))

for (j in 1:((nrows)-1)){
  for (n in (2*(j)):length(s)){
    Differences[(j),n] <- (-1)*((mean(Averages[1, (n-((2*j)-1)):(n-j)])-mean(Averages[1, (n-(j)+1):n]))/2)
  }
}

```

#Daubechies Wavelets (pkg: Wavelets)
```{r}
#First Iteration
#declare signal
s <- c(8,20,32,36,32,20,8,4)

#designate level, transform method, 
Sd4.dwt <- wt.filter(filter="d4", level=2)
str(Sd4.dwt)

#run the forward D4 transform
wt.dwt <- dwt.forward(s, Sd4.dwt)
str(wt.dwt)

#reconstruct signal from scaling/ wavelet coeffiecients 
newS.dwt <- dwt.backward(wt.dwt$W, wt.dwt$V, Sd4.dwt)

#run the forward D4 transform 2nd Time
wt.dwt_1 <- dwt.forward(wt.dwt$V, Sd4.dwt)



```
#Daubechies Wavelets (By hand matrix calculation)
```{r}
h0 <- (1+sqrt(3))/(4*sqrt(2))
h1 <- (3+sqrt(3))/(4*sqrt(2))
h2 <- (3-sqrt(3))/(4*sqrt(2))
h3 <- (1-sqrt(3))/(4*sqrt(2))

g0 <- h3
g1 <- -h2
g2 <- h1
g3 <- -h0

w_1 <- matrix(c(h3,h2,h1,h0,0,0,0,0,0,0,h3,h2,h1,h0,0,0,0,0,0,0,h3,h2,h1,h0,h1,h0,0,0,0,0,h3,h2,g3,g2,g1,g0,0,0,0,0,0,0,g3,g2,g1,g0,0,0,0,0,0,0,g3,g2,g1,g0,g1,g0,0,0,0,0,g3,g2),8,8, byrow = T)

w_2 <- matrix(c(h3,h2,h1,h0,0,0,0,0,h1,h0,h3,h2,0,0,0,0,g3,g2,g1,g0,0,0,0,0,g1,g0,g3,g2,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1),8,8, byrow = T)

s <- matrix(c(8,20,32,36,32,20,8,4),8,1)

p_other <- w_2 %*% w_1 %*% s
```


#Daubechies Wavelets (pkg: Wavethresh)
```{r}
s <- matrix(c(8,20,32,36,32,20,8,4),8,1)

Sd4_1.obj <- wd(data=s, filter.number=2, family="DaubExPhase",
type="wavelet", bc="periodic", verbose=FALSE)

Sd4_1.obj

filter.select(filter.number = 2, family = "DaubExPhase", constant = 1)

accessC (Sd4_1.obj, level = 2, boundary = T)
accessD (Sd4_1.obj, level = 2, boundary = T)

accessC (Sd4_1.obj, level = 1, boundary = T)
accessD (Sd4_1.obj, level = 1, boundary = T)

accessC (Sd4_1.obj, level = 0, boundary = T)
accessD (Sd4_1.obj, level = 0, boundary = T)

#W2<- t(GenW(n=8, filter.number=2, family = "DaubExPhase"))

```
