---
title: "Haar Wavelet Analysis"
author: "Zach Diener"
date: "June 4, 2015"
output: html_document
---
#Background Motivation
 I will be working to create code that will analyze a signal using Haar Wavelets. I am doing this in order to pick out features of signals that may be used as inputs into a neural network I will construct at a later point. 

#Attempt to model the table in Enhanced Brain Wave Analysis 
```{r}
n=length(Row_1)
i=c(1:(n-1))
Row_1=as.numeric(list(-12,0,12,16,12,0,-12,-16))
fRow_2=function(Row_1){(Row_1[i]+ Row_1[i+1])*.5}
Row_2=fRow_2(Row_1)
fRow_3=function(Row_2){(Row_2[i]+Row_2[i+2])*.5}
Row_3=fRow_3(Row_2)
fRow_4=function(Row_3){(Row_3[i]+Row_3[i+4])*.5}
Row_4=fRow_4(Row_3)

Row_1A-1
Row_2
Row_3
Row_4

```



```{r}
Averages=data.frame( Row_1 = c(-12,0,12,16,12,0,-12,-16))
n=length(Row_1)
i=c(1:(n))
fRow_1 <- function(Averages,Row_2){
  Row_2=c()
  for (i in 1:n){ 
    if(i==1){Row_2[1]=Row_1[1]*.5} 
    else {Row_2[i]=(Row_1[i-1]+Row_1[i])*.5}} 
  return(Row_2)
  unlist(Row_2)}
fRow_1(Averages,Row_2)
Averages$Row_2 <- fRow_1(Averages,Row_2)


fRow_2 <- function(Averages,Row_3){
  Row_3=c()
  Row_2=Averages$Row_2
  for (i in 1:n){ 
    if(i==1||i==2){Row_3[i]=Row_2[i]*.5} 
    #print(Row_3) 
    else {Row_3[i]=(Row_2[i-2]+Row_2[i])*.5}} 
  return(Row_3)}
Averages$Row_3 <- fRow_2(Averages,Row_3)

fRow_3 <- function(Averages,Row_4){
  Row_4=c()
  Row_3=Averages$Row_3
  for (i in 1:n){ 
    if(i==1||i==2||i==3||i==4){Row_4[i]=Row_3[i]*.5} 
    #print(Row_4) 
    else {Row_4[i]=(Row_3[i-4]+Row_3[i])*.5}} 
  return(Row_4)}
Averages$Row_4 <- fRow_3(Averages,Row_4)

Averages

```


